blank_issues_enabled: false
contact_links:
  - name: سؤال أو دعم | Question or Support
    url: mailto:abo.saleh.g@gmail.com
    about: للأسئلة العامة أو الدعم، راسلنا عبر البريد الإلكتروني | For general questions or support, contact us via email
